// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2btEb-jca3dwlBja8FR9-9ViMSb47kOg',
    appId: '1:1080956540196:web:edd2a4feba511948714fb1',
    messagingSenderId: '1080956540196',
    projectId: 'facebookauthapp-46697',
    authDomain: 'facebookauthapp-46697.firebaseapp.com',
    storageBucket: 'facebookauthapp-46697.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU8XYm864uq54CQnW23FQshOLG_6avEHI',
    appId: '1:1080956540196:android:9d23477717499e67714fb1',
    messagingSenderId: '1080956540196',
    projectId: 'facebookauthapp-46697',
    storageBucket: 'facebookauthapp-46697.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNUPYwYgC5ZFgJrfuSwARgS395zEiDP_8',
    appId: '1:1080956540196:ios:63b5809c9b2aeed3714fb1',
    messagingSenderId: '1080956540196',
    projectId: 'facebookauthapp-46697',
    storageBucket: 'facebookauthapp-46697.appspot.com',
    iosBundleId: 'com.example.facebookAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNUPYwYgC5ZFgJrfuSwARgS395zEiDP_8',
    appId: '1:1080956540196:ios:2c329c9d393e4a4a714fb1',
    messagingSenderId: '1080956540196',
    projectId: 'facebookauthapp-46697',
    storageBucket: 'facebookauthapp-46697.appspot.com',
    iosBundleId: 'com.example.facebookAuthApp.RunnerTests',
  );
}
